---
title: "Publications"

---
<body style="background-color:black">

<p style="font-family: times, serif; font-size:50pt; text-align: center; color:#5d5e0b">
    **Publications**
</p>
<p style="font-family: times, serif; font-size:20pt; text-align: center; color:white">
    [<i class="fa fa-graduation-cap"></i>](https://scholar.google.com/citations?user=WuPS8K0AAAAJ&hl=en) | [<i class="fab fa-researchgate"></i>](https://www.researchgate.net/profile/Jorge-D-Carballo-Morales)
</p>

<p style="font-family: accanthis; font-size:15pt; text-align: right; color:white">
  Under review
    </p>

<p style="font-family: accanthis; font-size:11pt; text-align: left; color:white">
  **Bats in tropical cities: a view since the ecology _in_, _of_ and _for_ cities.** || Saldaña-Vázquez, R. A., **Carballo-Morales, J. D.**, Hernández-Montero, J. R., Ríos-Chelén, A. A., Vázquez-Domínguez. G., Aguilar-Cucurachi, S., Avila-Flores, R., Mella-Mendez, I., Sandoval-Ruiz, C. A., Silva-Rivera. E., Schondube, J. E., Spaan, D. || *In: Angeoletto, F., Tryjanowski. P., Fellowes. M. (eds) Ecology of Tropical Cities: Natural and Social Sciences Applied to the Conservation of Urban Biodiversity. Springer.*
    </p>

<p style="font-family: accanthis; font-size:15pt; text-align: right; color:white">
  In prep
    </p>

<p style="font-family: accanthis; font-size:11pt; text-align: left; color:white">
  **Habitat breadth and its relation to functional traits and extinction risk in phyllostomid bats.** || **Carballo-Morales, J. D.**, Villalobos, F., Saldaña-Vázquez, R. A, Herrera-Alsina, L.
    </p>

<p style="font-family: accanthis; font-size:11pt; text-align: left; color:white">
  **Thermal niche breadth in Sturnira bats and their relation with species diversification.** || **Carballo-Morales, J. D.**, Saldaña-Vázquez, R. A., Villalobos, F., Herrera-Alsina, L.
    </p>

<p style="font-family: accanthis; font-size:11pt; text-align: left; color:white">
  **Thermal energetics of bats of the family Vespertilionidae: an evolutionary approach.** || Medina-Bello, K. I., **Carballo-Morales, J. D.**, Saldaña-Vázquez. R. A., Villalobos, F., Ayala-Berdon, J.
    </p>

<p style="font-family: accanthis; font-size:15pt; text-align: right; color:white">
  2022
    </p>

<p style="font-family: accanthis; font-size:11pt; text-align: left; color:white">
  **Niche partitioning and intraspecific shared webs in two species of _Modisimus_ Simon, 1893 (Pholcidae, Araneae).** || **Carballo-Morales, J. D.**, Delgado-Montes, C., Auccacusi-Choque, L. V., Reyes-Ortiz, M., Aisenberg, A. || *Journal of Arachnology.*
    </p>
    
<p style="font-family: accanthis; font-size:15pt; text-align: right; color:white">
  2021
    </p>

<p style="font-family: accanthis; font-size:11pt; text-align: left; color:white">
  **Body mass explains digestive traits in small vespertilionid bats.** || Cabrera-Campos, I., **Carballo-Morales, J. D.**, Saldaña-Vázquez, R. A., Villalobos, F., Ayala-Berdon, J. || *Journal of Comparative Physiology B.*
    </p>
    
<p style="font-family: accanthis; font-size:11pt; text-align: left; color:white">
  **Trophic guild and forest type explain phyllostomid bat abundance variation from human habitat disturbance.** || **Carballo-Morales, J. D.**, Saldaña-Vazquez, R. A., & Villalobos, F. || *Global Ecology and Conservation.*
    </p>